#!/usr/bin/env bash
#
# setup_msf_from_auto_recon.sh
#
# Bridge between auto_recon.sh and Metasploit:
# - Finds latest full_scan_*.xml
# - Detects eth0 IP
# - Generates setup/auto_msf_latest.rc for msfconsole
#
# Usage (from repo root):
#   ./auto_recon.sh
#   ./setup/setup_msf_from_auto_recon.sh
#   msfconsole -q -r setup/auto_msf_latest.rc
#

set -euo pipefail

SCAN_GLOB="full_scan_*.xml"
RC_PATH="setup/auto_msf_latest.rc"
LOG_DIR="logs"

mkdir -p "$LOG_DIR" setup

echo "[*] Looking for latest ${SCAN_GLOB} in current directory..."

latest_xml="$(ls -1t ${SCAN_GLOB} 2>/dev/null | head -n 1 || true)"

if [[ -z "${latest_xml}" ]]; then
  echo "[-] No ${SCAN_GLOB} files found. Did you run ./auto_recon.sh yet?"
  exit 1
fi

echo "[+] Using scan file: ${latest_xml}"

echo "[*] Detecting eth0 IP address..."
ETH0_IP=$(ip -4 -br a show eth0 2>/dev/null | awk '{print $3}' | cut -d'/' -f1)

if [[ -z "${ETH0_IP}" ]]; then
  echo "[-] Could not detect eth0 IPv4 address."
  ip -br a
  exit 1
fi

echo "[+] LHOST will be set to: ${ETH0_IP}"

TS="$(date +%Y%m%d_%H%M%S)"

echo "[*] Generating Metasploit RC at ${RC_PATH}..."

cat > "${RC_PATH}" <<EOF
# Auto-generated Metasploit setup RC
# Generated by: setup/setup_msf_from_auto_recon.sh
# Timestamp: ${TS}

spool ${LOG_DIR}/msf_from_auto_recon_${TS}.log

# Create and switch to a workspace for this run
workspace -a auto_${TS}
workspace auto_${TS}

# Set global LHOST based on eth0 IP
setg LHOST ${ETH0_IP}

# Global quality-of-life settings
setg ExitOnSession false
setg VERBOSE true

# Import the latest full_scan XML from auto_recon.sh
db_import ${latest_xml}

# Show imported data
hosts
services

spool off

echo "[*] MSF environment ready. Workspace: auto_${TS}, LHOST: ${ETH0_IP}, XML: ${latest_xml}"
EOF

echo "[+] Done."
echo
echo "Next steps:"
echo "  1) Launch Metasploit:"
echo "       msfconsole -q -r ${RC_PATH}"
echo "  2) Use 'hosts' and 'services' to pivot into protocol RCs (smb, winrm, etc.)."

