#!/usr/bin/env bash
#
# Auto local network scan + Metasploit RC generator
# - Detects IPs on eth0 and eth1
# - Scans corresponding /24s with nmap -sn
# - Runs deep scan (-sV -sC -O --script=discovery) on live hosts
# - Saves output as XML
# - Generates setup/auto_msf_latest.rc with:
#     * setg LHOST <your_ip>
#     * workspace creation
#     * db_import of the latest XML
#
# Run from repo root:
#   sudo ./setup/auto_nmap_local.sh

set -euo pipefail

# ---------- Config ----------
IFACES=("eth0" "eth1")     # Add tun0, wlan0 later if you want
SCAN_DIR="scans"
LOG_DIR="logs"
RC_PATH="setup/auto_msf_latest.rc"

# ---------- Checks ----------
if [[ "$EUID" -ne 0 ]]; then
  echo "[-] Please run this script with sudo/root (nmap needs raw sockets)."
  exit 1
fi

# Ensure we’re in repo root (simple sanity check)
if [[ ! -d "setup" || ! -d "protocols" ]]; then
  echo "[-] Run this from the repo root (where 'setup/' and 'protocols/' exist)."
  exit 1
fi

mkdir -p "$SCAN_DIR" "$LOG_DIR"

TS="$(date +%Y%m%d_%H%M%S)"
BASE="${SCAN_DIR}/local_${TS}"

# ---------- Find IPs & /24 networks ----------
declare -a NETS=()
LHOST_IP=""

for iface in "${IFACES[@]}"; do
  if ip -br addr show "$iface" &>/dev/null; then
    # Example: "eth0    UP   10.11.12.34/24 ..."
    line="$(ip -br addr show "$iface" | awk 'NR==1 {print $3}')"
    # line like "10.11.12.34/24"
    ip_addr="${line%/*}"

    # Save first usable IP as LHOST
    if [[ -z "$LHOST_IP" ]]; then
      LHOST_IP="$ip_addr"
    fi

    # Force /24 network from IP: X.Y.Z.0/24
    net="${ip_addr%.*}.0/24"
    NETS+=("$net")

    echo "[*] Detected ${iface}: IP=${ip_addr}, NET=${net}"
  fi
done

if [[ ${#NETS[@]} -eq 0 ]]; then
  echo "[-] No IPs found on eth0/eth1. Adjust IFACES array in this script if needed."
  exit 1
fi

echo "[*] Using LHOST IP: ${LHOST_IP}"

# ---------- Step 1: Host discovery with nmap -sn ----------
HOSTS_FILE="${BASE}_hosts.txt"
> "$HOSTS_FILE"

for net in "${NETS[@]}"; do
  echo "[*] Scanning network for live hosts: ${net}"
  # -oG - = grepable output to stdout
  nmap -sn "$net" -oG - | awk '/Up$/{print $2}' >> "$HOSTS_FILE"
done

# Unique hosts
sort -u "$HOSTS_FILE" -o "$HOSTS_FILE"

if [[ ! -s "$HOSTS_FILE" ]]; then
  echo "[-] No live hosts found in detected networks."
  exit 0
fi

echo "[*] Live hosts discovered:"
cat "$HOSTS_FILE"
echo

mapfile -t HOSTS < "$HOSTS_FILE"

# ---------- Step 2: Deep scan on live hosts ----------
echo "[*] Running deep scan on discovered hosts..."
echo "    nmap -sV -sC -O --script=default,discovery -oA ${BASE}_full ${HOSTS[*]}"

nmap -sV -sC -O --script=default,discovery -oA "${BASE}_full" "${HOSTS[@]}"

XML_PATH="${BASE}_full.xml"
if [[ ! -f "$XML_PATH" ]]; then
  echo "[-] Expected XML not found at ${XML_PATH}"
  exit 1
fi

# Symlink to "latest" for easy importing
ln -sfn "$(basename "$XML_PATH")" "${SCAN_DIR}/latest.xml"

echo "[*] Nmap scan complete."
echo "    XML: ${XML_PATH}"
echo "    Latest symlink: ${SCAN_DIR}/latest.xml"

# ---------- Step 3: Generate Metasploit RC ----------
echo "[*] Generating Metasploit RC at ${RC_PATH}"

cat > "$RC_PATH" <<EOF
# Auto-generated Metasploit setup RC
# Generated by: setup/auto_nmap_local.sh
# Timestamp: ${TS}

spool ${LOG_DIR}/msf_auto_${TS}.log

# Create and switch to a workspace for this run
workspace -a auto_${TS}
workspace auto_${TS}

# Set global LHOST based on detected interface IP
setg LHOST ${LHOST_IP}

# Tweak some global options (customize as you like)
setg ExitOnSession false
setg VERBOSE true

# Import latest Nmap scan
db_import ${XML_PATH}

# Show what we imported
hosts
services

spool off

echo "[*] Auto MSF setup complete. Workspace: auto_${TS}, LHOST: ${LHOST_IP}"
EOF

echo "[*] Done."
echo
echo "Next steps:"
echo "  1) cd to repo root (if not already here)."
echo "  2) Start Metasploit with:"
echo "       msfconsole -q -r ${RC_PATH}"
echo "  3) Use 'hosts' and 'services' to pivot into specific modules."

